# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG PROJECT_NAME
WORKDIR /target

COPY /target .
COPY /source .

RUN ls -lR
RUN echo $PROJECT_NAME
RUN dotnet sln add $PROJECT_NAME/*.csproj
