# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG PROJECT_NAME
ARG SOURCE_PATH
ARG TARGET_PATH
WORKDIR $TARGET_PATH

COPY $TARGET_PATH .
COPY $SOURCE_PATH .

RUN dotnet sln add $PROJECT_NAME/*.csproj

# This target generates the files for output.
FROM scratch AS export
COPY --from=build $TARGET_PATH /
