apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-dotnet-project-v1.0
  title: .NET project EXTENSION
  description: Add a .NET 6 project to an existing repository
spec:
  owner: Team Platform
  type: api
  parameters:
    - title: Choose the SOURCE component
      properties:
        sourceEntity:
          title: Source component
          type: string
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Template
            allowArbitraryValues: false

    - title: Choose the TARGET repository
      properties:
        targetRepoUrl:
          title: Target repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: debug
      name: Debug
      action: debug:log
      input:
        message: ${{ parameters | dump }}

    - id: sourceEntityRefResolver
      name: Locate Source
      action: catalog:get
      input:
        entityRef: ${{ parameters.sourceEntity }}

    - id: debug2
      name: Debug
      action: debug:log
      input:
        message: ${{ steps | dump }}

    - id: fetchSource
      name: Fetch Source
      action: fetch:template
      input:
        url: ${{ steps.sourceEntityRefResolver.output.entity.metadata.annotations["backstage.io/source-location"] | replace("url:", "", 1) }}/template
        values:
          name: 'ProjectName'

    - id: fetchTarget
      name: Fetch Target
      action: fetch:plain
      input:
        url: ${{ parameters.targetRepoUrl }}

    - id: dockerProcessor
      name: Updating
      action: process:docker
      input:
        url: ${{ steps.sourceEntityRefResolver.output.entity.metadata.annotations["backstage.io/source-location"] | replace("url:", "", 1) }}/Dockerfile.backstage.add }}
        entityRef: ${{ parameters.sourceEntity }}
